export const appConfig = {
  port: parseInt(process.env.PORT ?? '3000', 10),
  nodeEnv: process.env.NODE_ENV || 'development',
  jwtSecret: process.env.JWT_SECRET || 'fallback-secret',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || '15m',
  jwtRefreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '30d',
  redisHost: process.env.REDIS_HOST || 'localhost',
  redisPort: parseInt(process.env.REDIS_PORT ?? '6379', 10),
  sparrowToken: process.env.SPARROW_TOKEN || '',
  sparrowFrom: process.env.SPARROW_FROM || 'YatraGo',
  googleMapsKey: process.env.GOOGLE_MAPS_API_KEY || '',
  esewaBaseUrl: process.env.ESEWA_BASE_URL || '',
  esewaMerchantId: process.env.ESEWA_MERCHANT_ID || '',
  esewaSecret: process.env.ESEWA_SECRET || '',
  khaltiBaseUrl: process.env.KHALTI_BASE_URL || '',
  khaltiSecretKey: process.env.KHALTI_SECRET_KEY || '',
  r2AccountId: process.env.R2_ACCOUNT_ID || '',
  r2AccessKey: process.env.R2_ACCESS_KEY || '',
  r2SecretKey: process.env.R2_SECRET_KEY || '',
  r2BucketName: process.env.R2_BUCKET_NAME || '',
  r2PublicUrl: process.env.R2_PUBLIC_URL || '',
};